"""added new model numbeer column for inventroy so quniness is there

Revision ID: 6de84d6b3c2b
Revises: ff07902356b9
Create Date: 2026-03-30 12:49:23.935619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de84d6b3c2b'
down_revision = 'ff07902356b9'
branch_labels = None
depends_on = None


def upgrade():
    # ✅ Step 1: Add column FIRST
    op.add_column(
        'inventory',
        sa.Column('model_number', sa.String(length=100), nullable=True)
    )

    # ✅ Step 2: Then create index
    op.create_index(
        op.f('ix_inventory_model_number'),
        'inventory',
        ['model_number'],
        unique=True
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_model_number'), table_name='inventory')
    # ### end Alembic commands ###
