"""remove extra id colmn

Revision ID: ff07902356b9
Revises: 001_initial
Create Date: 2026-03-29 19:34:24.285474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff07902356b9'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('product_id'), table_name='inventory')
    op.drop_column('inventory', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('product_id'), 'inventory', ['product_id'], unique=True)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    # ### end Alembic commands ###
