# =========================================================
# PRODUCTION CONFIGURATION
#
# docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
#
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
#
# =========================================================

services:
  # =========================================================
  # ZOOKEEPER
  # =========================================================

  zookeeper:
    ports:
      - "2181:2181"

  # =========================================================
  # KAFKA
  # =========================================================

  kafka:
    ports:
      - "9092:9092"

  # =========================================================
  # MYSQL
  # =========================================================

  mysql:
    ports:
      - "3307:3306"

  # =========================================================
  # ORDER SERVICE
  # =========================================================

  order-service:
    image: manishhd01/order-service:latest

    ports:
      - "8000:8000"

  # =========================================================
  # INVENTORY SERVICE
  # =========================================================

  inventory-service:
    image: manishhd01/inventory-service:latest

    ports:
      - "8001:8000"

  # =========================================================
  # CUSTOMER SERVICE
  # =========================================================

  customer-service:
    image: manishhd01/customer-service:latest

    ports:
      - "8002:8000"

  # =========================================================
  # PAYMENT SERVICE
  # =========================================================

  payment-service:
    image: manishhd01/payment-service:latest

    ports:
      - "8003:8000"

  # =========================================================
  # NOTIFICATION SERVICE
  # =========================================================

  notification-service:
    image: manishhd01/notification-service:latest

    ports:
      - "8004:8000"

  # =========================================================
  # SHIPPING SERVICE
  # =========================================================

  shipping-service:
    image: manishhd01/shipping-service:latest

    ports:
      - "8005:8000"

  # =========================================================
  # AI SERVICE
  # =========================================================
  ai-service:
    image: manishhd01/ai-service:latest
    ports:
      - "8007:8000"

  # =========================================================
  # FRONTEND
  # =========================================================

  frontend:
    image: manishhd01/frontend:latest

    ports:
      - "80:80"

  # =========================================================
  # LOKI
  # =========================================================

  loki:
    ports:
      - "3100:3100"

  # =========================================================
  # GRAFANA
  # =========================================================

  grafana:
    ports:
      - "3001:3000"
