# =========================================================
# BASE DOCKER COMPOSE CONFIGURATION
#
# This file contains common configuration shared by
# development and production.
#
# DEV:
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
#
# PROD:
# docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
#
# Jenkins:
# docker compose build
#
# =========================================================

# ---------------------------------------------------------old file

# # version: "3.9"

services:
  # =========================================================
  # ZOOKEEPER
  # =========================================================

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    restart: unless-stopped
    container_name: zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

  # =========================================================
  # KAFKA
  # =========================================================

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    restart: unless-stopped
    container_name: kafka

    depends_on:
      - zookeeper

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_HEAP_OPTS: "-Xms256M -Xmx256M" #to take leess space:

    volumes:
      - kafka_data:/var/lib/kafka/data

  # =========================================================
  # MYSQL
  # =========================================================

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root

    command:
      - --innodb-buffer-pool-size=128M #to take leess space:

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  # =========================================================
  # ORDER SERVICE
  # =========================================================

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile

    image: manishhd01/order-service:latest

    container_name: order-service
    restart: unless-stopped

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      PORT: 8000
      DB_NAME: order_db

    depends_on:
      mysql:
        condition: service_started

  # =========================================================
  # INVENTORY SERVICE
  # =========================================================

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile

    image: manishhd01/inventory-service:latest

    container_name: inventory-service
    restart: unless-stopped

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      PORT: 8000
      DB_NAME: inventory_db

    depends_on:
      mysql:
        condition: service_started

  # =========================================================
  # PAYMENT SERVICE
  # =========================================================

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile

    image: manishhd01/payment-service:latest

    container_name: payment-service
    restart: unless-stopped

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      PORT: 8000
      DB_NAME: payment_db

    depends_on:
      mysql:
        condition: service_started

  # =========================================================
  # CUSTOMER SERVICE
  # =========================================================

  customer-service:
    build:
      context: .
      dockerfile: customer-service/Dockerfile

    image: manishhd01/customer-service:latest

    container_name: customer-service
    restart: unless-stopped

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      PORT: 8000
      DB_NAME: customer_db

    depends_on:
      mysql:
        condition: service_started

  # =========================================================
  # NOTIFICATION SERVICE
  # =========================================================

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile

    image: manishhd01/notification-service:latest

    container_name: notification-service
    restart: unless-stopped

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      PORT: 8000
      DB_NAME: notification_db

    depends_on:
      mysql:
        condition: service_started

      kafka:
        condition: service_started

  # =========================================================
  # SHIPPING SERVICE
  # =========================================================

  shipping-service:
    build:
      context: .
      dockerfile: shipping-service/Dockerfile

    image: manishhd01/shipping-service:latest

    container_name: shipping-service
    restart: unless-stopped

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      PORT: 8000
      DB_NAME: shipping_db

    depends_on:
      mysql:
        condition: service_started

      kafka:
        condition: service_started

  # =========================================================
  # FRONTEND
  # =========================================================

  frontend:
    build:
      context: ./frontend

      args:
        REACT_APP_API_HOST: http://3.226.15.198
        REACT_APP_ENV: production

    image: manishhd01/frontend:latest

    container_name: frontend
    restart: unless-stopped

    stdin_open: true
    tty: true

    depends_on:
      - order-service
      - inventory-service
      - payment-service
      - customer-service
      - notification-service

    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules

    # environment:
    # - CHOKIDAR_USEPOLLING=true
    # - WATCHPACK_POLLING=true
    # # - REACT_APP_ENV=development
    # - REACT_APP_ENV=production
    # - REACT_APP_API_HOST=http://3.226.15.198

  # =========================================================
  # LOKI
  # =========================================================

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    restart: unless-stopped

    command: -config.file=/etc/loki/local-config.yaml

  # =========================================================
  # PROMTAIL
  # =========================================================

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    restart: unless-stopped

    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml

    command: -config.file=/etc/promtail/config.yml

    depends_on:
      - loki

  # =========================================================
  # GRAFANA
  # =========================================================

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped

    depends_on:
      - loki

    volumes:
      - grafana_data:/var/lib/grafana

# =========================================================
# VOLUMES
# =========================================================

volumes:
  mysql_data:
  grafana_data:
  kafka_data:
  zookeeper_data:
  zookeeper_log:

# # services:
# # test comment:

# ---------------------------------------------------------old file

# # version: "3.9"

# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.2.1
#     restart: unless-stopped
#     container_name: zookeeper
#     ports:
#       - "2181:2181"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     volumes:
#       - zookeeper_data:/var/lib/zookeeper/data
#       - zookeeper_log:/var/lib/zookeeper/log

#   kafka:
#     image: confluentinc/cp-kafka:7.2.1
#     restart: unless-stopped
#     container_name: kafka
#     ports:
#       - "9092:9092"
#     depends_on:
#       - zookeeper
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#       KAFKA_HEAP_OPTS: "-Xms256M -Xmx256M" #to take leess space:
#     volumes:
#       - kafka_data:/var/lib/kafka/data

#   mysql:
#     image: mysql:8.0
#     restart: unless-stopped
#     container_name: mysql
#     ports:
#       - "3307:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#     command:
#       - --innodb-buffer-pool-size=128M #to take leess space:
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 5s
#       timeout: 10s
#       retries: 10

#   order-service:
#     build:
#       context: .
#       dockerfile: order-service/Dockerfile
#     container_name: order-service
#     image: manishhd01/order-service:latest
#     restart: unless-stopped
#     ports:
#       - "8000:8000"
#     environment:
#       - DB_HOST=mysql
#       - DB_PORT=3306
#       - PORT=8000
#       - DB_NAME=order_db
#     depends_on:
#       mysql:
#         condition: service_started
#     volumes:
#       - ./order-service:/app
#       - ./common_logging:/app/common_logging

#   inventory-service:
#     build:
#       context: .
#       dockerfile: inventory-service/Dockerfile
#     image: manishhd01/inventory-service:latest
#     restart: unless-stopped
#     container_name: inventory-service
#     ports:
#       - "8001:8000"
#     environment:
#       - DB_HOST=mysql
#       - DB_PORT=3306
#       - PORT=8000
#       - DB_NAME=inventory_db
#     depends_on:
#       mysql:
#         condition: service_started
#     volumes:
#       - ./inventory-service:/app
#       - ./common_logging:/app/common_logging

#   payment-service:
#     build:
#       context: .
#       dockerfile: payment-service/Dockerfile
#     image: manishhd01/payment-service:latest
#     restart: unless-stopped
#     container_name: payment-service
#     ports:
#       - "8003:8000"

#     environment:
#       - DB_HOST=mysql
#       - DB_PORT=3306
#       - PORT=8000
#       - DB_NAME=payment_db
#     depends_on:
#       mysql:
#         condition: service_started
#     volumes:
#       - ./payment-service:/app
#       - ./common_logging:/app/common_logging

#   customer-service:
#     build:
#       context: .
#       dockerfile: customer-service/Dockerfile
#     image: manishhd01/customer-service:latest
#     restart: unless-stopped
#     container_name: customer-service
#     ports:
#       - "8002:8000"

#     environment:
#       - DB_HOST=mysql
#       - DB_PORT=3306
#       - PORT=8000
#       - DB_NAME=customer_db
#     depends_on:
#       mysql:
#         condition: service_started
#     volumes:
#       - ./customer-service:/app
#       - ./common_logging:/app/common_logging
#   notification-service:
#     build:
#       context: .
#       dockerfile: notification-service/Dockerfile
#     image: manishhd01/notification-service:latest
#     container_name: notification-service
#     restart: unless-stopped
#     ports:
#       - "8004:8000"

#     environment:
#       - DB_HOST=mysql
#       - DB_PORT=3306
#       - PORT=8000
#       - DB_NAME=notification_db
#     depends_on:
#       mysql:
#         condition: service_started
#       kafka:
#         condition: service_started
#     volumes:
#       - ./notification-service:/app
#       - ./common_logging:/app/common_logging

#   shipping-service:
#     build:
#       context: .
#       dockerfile: shipping-service/Dockerfile
#     container_name: shipping-service
#     image: manishhd01/shipping-service:latest
#     restart: unless-stopped
#     ports:
#       - "8005:8000"
#     environment:
#       - DB_HOST=mysql
#       - DB_PORT=3306
#       - PORT=8000
#       - DB_NAME=shipping_db
#     depends_on:
#       mysql:
#         condition: service_started
#       kafka:
#         condition: service_started
#     volumes:
#       - ./shipping-service:/app
#       - ./common_logging:/app/common_logging

#   frontend:
#     build:
#       context: ./frontend
#       args:
#         REACT_APP_API_HOST: http://3.226.15.198
#         REACT_APP_ENV: production
#     container_name: frontend
#     image: manishhd01/frontend:latest
#     restart: unless-stopped
#     ports:
#       # - "3000:3000"
#       - "80:80"
#     stdin_open: true
#     tty: true
#     depends_on:
#       - order-service
#       - inventory-service
#       - payment-service
#       - customer-service
#       - notification-service

#     # volumes:
#     #   - ./frontend:/app
#     #   - /app/node_modules
#     # environment:
#     # - CHOKIDAR_USEPOLLING=true
#     # - WATCHPACK_POLLING=true
#     # # - REACT_APP_ENV=development
#     # - REACT_APP_ENV=production
#     # - REACT_APP_API_HOST=http://3.226.15.198

#   loki:
#     image: grafana/loki:2.9.8
#     container_name: loki
#     restart: unless-stopped
#     ports:
#       - "3100:3100"

#     command: -config.file=/etc/loki/local-config.yaml

#   promtail:
#     image: grafana/promtail:2.9.8
#     container_name: promtail
#     restart: unless-stopped
#     volumes:
#       - /var/lib/docker/containers:/var/lib/docker/containers:ro
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./promtail-config.yml:/etc/promtail/config.yml

#     command: -config.file=/etc/promtail/config.yml

#     depends_on:
#       - loki

#   grafana:
#     image: grafana/grafana:10.4.2
#     container_name: grafana
#     restart: unless-stopped
#     ports:
#       - "3001:3000"

#     depends_on:
#       - loki

#     volumes:
#       - grafana_data:/var/lib/grafana

# volumes:
#   mysql_data:
#   grafana_data:
#   kafka_data:
#   zookeeper_data:
#   zookeeper_log:

# # services:

# # test comment:
