# =========================================================
# DEVELOPMENT CONFIGURATION
#
# Start:
#
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up     #  do not build
#
# # docker compose --env-file .env.development -f docker-compose.yml -f docker-compose.dev.yml up ai-service                   ====starting container:

# =========================================================

services:
  # =========================================================
  # ZOOKEEPER
  # =========================================================

  zookeeper:
    ports:
      - "2181:2181"

  # =========================================================
  # KAFKA
  # =========================================================
  kafka-ui:
    ports:
      - "8086:8080" #no need to aadd in prod docker. casue willl not exposee..
  kafka:
    ports:
      - "9092:9092"

  # =========================================================
  # MYSQL
  # =========================================================

  mysql:
    ports:
      - "3307:3306"

  # =========================================================
  # ORDER SERVICE
  # =========================================================

  order-service:
    image: manishhd01/order-service:dev

    ports:
      - "8000:8000"

    volumes:
      - ./order-service:/app
      - ./common_logging:/app/common_logging

  # =========================================================
  # INVENTORY SERVICE
  # =========================================================

  inventory-service:
    image: manishhd01/inventory-service:dev

    ports:
      - "8001:8000"

    volumes:
      - ./inventory-service:/app
      - ./common_logging:/app/common_logging

  # =========================================================
  # CUSTOMER SERVICE
  # =========================================================

  customer-service:
    image: manishhd01/customer-service:dev

    ports:
      - "8002:8000"

    volumes:
      - ./customer-service:/app
      - ./common_logging:/app/common_logging

  # =========================================================
  # PAYMENT SERVICE
  # =========================================================

  payment-service:
    image: manishhd01/payment-service:dev

    ports:
      - "8003:8000"

    volumes:
      - ./payment-service:/app
      - ./common_logging:/app/common_logging

  # =========================================================
  # NOTIFICATION SERVICE
  # =========================================================

  notification-service:
    image: manishhd01/notification-service:dev

    ports:
      - "8004:8000"

    volumes:
      - ./notification-service:/app
      - ./common_logging:/app/common_logging

  # =========================================================
  # SHIPPING SERVICE
  # =========================================================

  shipping-service:
    image: manishhd01/shipping-service:dev

    ports:
      - "8005:8000"

    volumes:
      - ./shipping-service:/app
      - ./common_logging:/app/common_logging

  # =========================================================
  # AI SERVICE
  # =========================================================

  ai-service:
    ports:
      - "8007:8000"

    environment:
      ENVIRONMENT: development

    volumes:
      - ./ai-service/data/chroma:/app/data/chroma
      - ./ai-service/app:/app/app
      - ./ai-service/knowledge:/app/knowledge
      - ai_huggingface_cache:/root/.cache/huggingface
      - ai_pip_cache:/root/.cache/pip

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # =========================================================
  # FRONTEND
  # =========================================================

  frontend:
    image: manishhd01/frontend:dev

    build:
      context: ./frontend
      target: development
      args:
        REACT_APP_API_HOST: ${REACT_APP_API_HOST}
        REACT_APP_ENV: ${REACT_APP_ENV}

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_ENV: ${REACT_APP_ENV}

  # =========================================================
  # LOKI
  # =========================================================

  loki:
    ports:
      - "3100:3100"

  # =========================================================
  # GRAFANA
  # =========================================================

  grafana:
    ports:
      - "3001:3000"
