"""add order number

Revision ID: 30491bdc7e57
Revises: 001_initial
Create Date: 2026-08-18 11:26:49.709641

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "30491bdc7e57"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:

    # 1. Allow NULL temporarily so existing rows don't break
    op.alter_column(
        "orders",
        "order_number",
        existing_type=mysql.VARCHAR(length=50),
        nullable=True,
    )

    # 2. Backfill existing orders
    op.execute("""
        UPDATE orders
        SET order_number = CONCAT('ORD-', LPAD(id, 8, '0'))
        WHERE order_number IS NULL OR order_number = ''
    """)

    # 3. Create UNIQUE index after all existing rows have unique values
    op.create_index(
        op.f("ix_orders_order_number"),
        "orders",
        ["order_number"],
        unique=True,
    )

    # 4. Once everything is populated, make it NOT NULL
    op.alter_column(
        "orders",
        "order_number",
        existing_type=mysql.VARCHAR(length=50),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_order_number"), table_name="orders")
    op.alter_column(
        "orders", "order_number", existing_type=mysql.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
