"""brand new schema_upgrade_ 12 july

Revision ID: 893d0e420771
Revises: d8adcbb5f6ce
Create Date: 2026-07-12 11:16:16.246166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893d0e420771'
down_revision: Union[str, None] = 'd8adcbb5f6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
