"""added shipping tracking table

Revision ID: a978224aba31
Revises: c9eefcd56e61
Create Date: 2026-04-18 17:53:02.144972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a978224aba31"
down_revision: Union[str, None] = "c9eefcd56e61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment_tracking",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shipment_id", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("lat", sa.String(length=50), nullable=True),
        sa.Column("lng", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shipment_tracking_id"), "shipment_tracking", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_shipment_tracking_shipment_id"),
        "shipment_tracking",
        ["shipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shipment_tracking_timestamp"),
        "shipment_tracking",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_shipment_tracking_timestamp"), table_name="shipment_tracking"
    )
    op.drop_index(
        op.f("ix_shipment_tracking_shipment_id"), table_name="shipment_tracking"
    )
    op.drop_index(op.f("ix_shipment_tracking_id"), table_name="shipment_tracking")
    op.drop_table("shipment_tracking")
    # ### end Alembic commands ###
