"""add return and replacement timestamps

Revision ID: e143b237754c
Revises: f4fb9d488519
Create Date: 2026-04-20 19:35:36.073758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e143b237754c'
down_revision: Union[str, None] = 'f4fb9d488519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('return_requested_at', sa.DateTime(), nullable=True))
    op.add_column('shipments', sa.Column('returned_at', sa.DateTime(), nullable=True))
    op.add_column('shipments', sa.Column('replacement_requested_at', sa.DateTime(), nullable=True))
    op.add_column('shipments', sa.Column('replaced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'replaced_at')
    op.drop_column('shipments', 'replacement_requested_at')
    op.drop_column('shipments', 'returned_at')
    op.drop_column('shipments', 'return_requested_at')
    # ### end Alembic commands ###
