"""creaetd both tables in db

Revision ID: f4fb9d488519
Revises: a978224aba31
Create Date: 2026-04-19 19:38:58.115241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f4fb9d488519"
down_revision: Union[str, None] = "a978224aba31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    pass


def downgrade():
    pass
    # new commente


# def upgrade() -> None:
#     op.add_column(
#         "shipment_tracking",
#         sa.Column(
#             "event_type", sa.String(length=20), nullable=False, server_default=""
#         ),
#     )


# def upgrade() -> None:
#     op.add_column(
#         "shipment_tracking",
#         sa.Column(
#             "event_type", sa.String(length=20), nullable=False, server_default=""
#         ),
#     )


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('shipments',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('order_id', sa.Integer(), nullable=False),
#     sa.Column('status', sa.String(length=20), nullable=False),
#     sa.Column('tracking_number', sa.String(length=100), nullable=True),
#     sa.Column('carrier', sa.String(length=50), nullable=True),
#     sa.Column('estimated_delivery', sa.DateTime(), nullable=True),
#     sa.Column('delivered_at', sa.DateTime(), nullable=True),
#     sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
#     sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     sa.UniqueConstraint('tracking_number')
#     )
#     op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
#     op.create_table('shipment_tracking',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('shipment_id', sa.Integer(), nullable=True),
#     sa.Column('event_type', sa.String(length=20), nullable=False),
#     sa.Column('location', sa.String(length=255), nullable=True),
#     sa.Column('status', sa.String(length=50), nullable=False),
#     sa.Column('description', sa.String(length=255), nullable=True),
#     sa.Column('timestamp', sa.DateTime(), nullable=True),
#     sa.Column('lat', sa.String(length=50), nullable=True),
#     sa.Column('lng', sa.String(length=50), nullable=True),
#     sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_shipment_tracking_id'), 'shipment_tracking', ['id'], unique=False)
#     op.create_index(op.f('ix_shipment_tracking_shipment_id'), 'shipment_tracking', ['shipment_id'], unique=False)
#     op.create_index(op.f('ix_shipment_tracking_timestamp'), 'shipment_tracking', ['timestamp'], unique=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_shipment_tracking_timestamp'), table_name='shipment_tracking')
#     op.drop_index(op.f('ix_shipment_tracking_shipment_id'), table_name='shipment_tracking')
#     op.drop_index(op.f('ix_shipment_tracking_id'), table_name='shipment_tracking')
#     op.drop_table('shipment_tracking')
#     op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
#     op.drop_table('shipments')
#     # ### end Alembic commands ###
